{{ if .Values.cloud_registry.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    {{- if .Values.cloud_registry.ingress.https.enabled }}
    cert-manager.io/cluster-issuer: {{ .Values.cloud_registry.ingress.https.issuer }}
    kubernetes.io/tls-acme: "true"
    {{- end }}
  name: {{ .Values.cloud_registry.appName }}
spec:
  rules:
  - host: {{ .Values.host_name }} 
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.cloud_registry.appName }} 
            port:
              number: 8080
{{- if .Values.cloud_registry.ingress.https.enabled }}
  tls:
  - hosts:
    - {{ .Values.host_name }}
    secretName: {{ .Values.cloud_registry.appName }}-ingress-secret
{{- end }}
{{ end }}
