# Default values for cloud-registry.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

host_name: ""

cloud_registry:
  image: elixircloud/cloud-registry:20240716
  appName: cloud-registry
  # if ingress.enabled: false, it will deploy an OpenShift Route (https://docs.redhat.com/en/documentation/openshift_container_platform/4.19/html/network_apis/route-route-openshift-io-v1)
  ingress:
    enabled: true
    https:
      enabled: false
      issuer: letsencrypt-prod
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi

apiServer: kubernetes.default.svc:443 # address of k8s API server

mongodb:
  image: docker.io/library/mongo:noble
  volumeSize: 1Gi
  resources:
    limits:
      cpu: 200m
      memory: 512Mi
    requests:
      cpu: 200m
      memory: 512Mi

